# Generated by Django 5.0.2 on 2024-03-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sport_name', models.CharField(max_length=100)),
            ],
        ),
    ]
