# Generated by Django 5.0.2 on 2024-03-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sport',
            new_name='sports',
        ),
    ]
