# Generated by Django 5.0.2 on 2024-04-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_sports_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('number_of_teams', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
