# Generated by Django 5.0.2 on 2024-06-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_facility'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
