# Generated by Django 5.0.6 on 2025-02-19 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_playertype_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_reco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('allrounder', 'All-rounder'), ('wicketkeeper', 'Wicketkeeper')], max_length=50)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(default=18)),
                ('nationality', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_average', models.FloatField(default=0.0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('total_runs', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('bowling_average', models.FloatField(default=0.0)),
                ('economy', models.FloatField(default=0.0)),
                ('matches_played', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('best_bowling_figures', models.CharField(blank=True, max_length=20, null=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.player')),
            ],
        ),
    ]
