# Generated by Django 5.0.6 on 2025-02-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_player_reco_playerstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='highest_score',
            new_name='match_experience',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='best_bowling_figures',
        ),
        migrations.RemoveField(
            model_name='playerstats',
            name='matches_played',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='fitness_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='recent_form',
            field=models.FloatField(default=0.0),
        ),
    ]
